name: Update M3U8 Playlist

on:
  schedule:
    - cron: "*/10 * * * *"
  push:
    branches:
      - main

jobs:
  update_playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install youtube-dl
      run: |
        sudo apt-get update
        sudo apt-get install -y youtube-dl

    - name: Run conversion script
      run: |
        chmod +x update_playlist.sh
        ./update_playlist.sh

    - name: Commit changes
      run: |
        git config --global user.name 'askan-2009'
        git config --global user.email 'akilaskan@gmail.com'
        git add playlist.m3u8
        git commit -m "Update M3U8 playlist" || echo "No changes to commit"
        git push
